# Generated by Django 4.0.5 on 2022-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorensicSiteGuestsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_name', models.TextField(null=True)),
                ('guests_email', models.TextField(null=True)),
                ('guests_project_description', models.TextField(null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corensic_site_guests_info',
            },
        ),
        migrations.CreateModel(
            name='CorensicSiteGuestVisitStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_ip', models.TextField(null=True)),
                ('guests_location', models.TextField(null=True)),
                ('guests_hostname', models.TextField(null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corensic_site_guest_visit_statistic',
            },
        ),
    ]
