# Generated by Django 4.0.5 on 2022-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORENSIC_site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorensicSiteErrorsStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_ip', models.TextField(null=True)),
                ('guests_location', models.TextField(null=True)),
                ('guests_hostname', models.TextField(null=True)),
                ('error_400', models.TextField(null=True)),
                ('error_403', models.TextField(null=True)),
                ('error_404', models.TextField(null=True)),
                ('error_500', models.TextField(null=True)),
            ],
            options={
                'db_table': 'corensic_site_errors_statistic',
            },
        ),
    ]
