# Generated by Django 4.0.5 on 2022-06-30 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CORENSIC_site_app', '0002_corensicsiteerrorsstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='corensicsiteerrorsstatistic',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corensicsiteerrorsstatistic',
            name='error_400',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corensicsiteerrorsstatistic',
            name='error_403',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corensicsiteerrorsstatistic',
            name='error_404',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corensicsiteerrorsstatistic',
            name='error_500',
            field=models.BooleanField(default=False),
        ),
    ]
